AllCops:
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 14

Naming/FileName:
  Exclude:
    - lib/rubocop-thread_safety.rb
    - rubocop-thread_safety.gemspec

# Enable more cops that are disabled by default:

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true
  Exclude:
    - spec/**/*

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true
