sudo: false
cache: bundler
language: ruby
rvm:
  - jruby-9.1.14.0
  - 2.3.0
  - 2.4
  - 2.5
  - 2.6
  - 2.7

matrix:
  fast_finish: true

before_install: gem install --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
