sudo: false
cache: bundler
language: ruby
rvm:
  - jruby-9.1.14.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4

matrix:
  fast_finish: true

before_install: gem install --remote bundler -v '1.17.3'
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
